import { motion } from 'framer-motion';
import { AlertCircle, CheckCircle2, ShieldAlert, FileDown, ScanHeart } from 'lucide-react';

export function AnalysisCard({
  isLoading,
  result,
  confidence,
  onReset,
  downloadUrl
}) {
  if (isLoading) {
    return (
      <div className="w-full h-[400px] glass-panel rounded-3xl p-8 flex flex-col items-center justify-center relative overflow-hidden">
        {/* Scanning line animation */}
        <div className="absolute inset-0 z-0">
          <motion.div
            initial={{ top: '-10%' }}
            animate={{ top: '110%' }}
            transition={{ duration: 2, repeat: Infinity, ease: 'linear' }}
            className="w-full h-1 bg-blue-500/50 shadow-[0_0_20px_rgba(59,130,246,1)]"
          />
        </div>
        
        <div className="relative z-10 flex flex-col items-center">
          <div className="w-24 h-24 rounded-full border-4 border-slate-700/50 flex items-center justify-center mb-6 relative">
            <motion.div
              animate={{ rotate: 360 }}
              transition={{ duration: 2, repeat: Infinity, ease: 'linear' }}
              className="absolute inset-0 rounded-full border-4 border-transparent border-t-blue-500 border-r-indigo-500"
            />
            <ScanHeart className="w-10 h-10 text-blue-400 animate-pulse" />
          </div>
          <motion.h3
            initial={{ opacity: 0, y: 10 }}
            animate={{ opacity: 1, y: 0 }}
            className="text-2xl font-bold text-transparent bg-clip-text bg-gradient-to-r from-blue-400 to-indigo-400 mb-2 drop-shadow-sm"
          >
            Analyzing X-Ray...
          </motion.h3>
          <motion.p
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            transition={{ delay: 0.2 }}
            className="text-slate-400"
          >
            Running deep learning model inferences
          </motion.p>
        </div>
      </div>
    );
  }

  if (!result) return null;

  const isPneumonia = result === 'Pneumonia';
  const colorClass = isPneumonia ? 'text-rose-400' : 'text-emerald-400';
  const bgGradient = isPneumonia
    ? 'from-rose-500/20 to-orange-500/5 border-rose-500/30'
    : 'from-emerald-500/20 to-teal-500/5 border-emerald-500/30';
  
  const Icon = isPneumonia ? ShieldAlert : CheckCircle2;

  return (
    <motion.div
      initial={{ opacity: 0, scale: 0.95 }}
      animate={{ opacity: 1, scale: 1 }}
      className="w-full glass-panel rounded-3xl p-8 flex flex-col"
    >
      <div className="flex items-start justify-between mb-8">
        <div>
          <h2 className="text-xl font-semibold text-slate-200 mb-1">
            Analysis Report
          </h2>
          <p className="text-sm text-slate-500">
            Generated by PneumoAI Vision Model v2.4
          </p>
        </div>
        <div className={`p-4 rounded-2xl border bg-gradient-to-br ${bgGradient} shadow-lg backdrop-blur-md`}>
          <Icon className={`w-8 h-8 ${colorClass} drop-shadow-[0_0_10px_rgba(currentColor,0.5)]`} />
        </div>
      </div>

      <div className="grid grid-cols-2 gap-4 mb-8">
        <div className="glass-card rounded-2xl p-5 flex flex-col">
          <span className="text-xs text-slate-500 font-medium uppercase tracking-wider mb-2">
            Diagnosis
          </span>
          <span className={`text-3xl font-bold tracking-tight ${colorClass} drop-shadow-sm`}>
            {result}
          </span>
          <p className="text-sm text-slate-400 mt-2">
            Model prediction based on lung opacities
          </p>
        </div>

        <div className="glass-card rounded-2xl p-5 flex flex-col justify-between">
          <div>
             <div className="flex justify-between items-center mb-2">
               <span className="text-xs text-slate-500 font-medium uppercase tracking-wider">
                 Confidence Score
               </span>
               <span className="text-xl font-bold text-slate-200">
                 {confidence}%
               </span>
             </div>
             
             {/* Progress bar container */}
             <div className="w-full h-3 bg-slate-900 rounded-full mt-4 overflow-hidden border border-slate-700/50 inset-shadow-sm">
                <motion.div
                  initial={{ width: 0 }}
                  animate={{ width: `${confidence}%` }}
                  transition={{ duration: 1.5, ease: "easeOut" }}
                  className={`h-full rounded-full ${
                    isPneumonia ? 'bg-gradient-to-r from-rose-600 to-rose-400' : 'bg-gradient-to-r from-emerald-600 to-emerald-400'
                  } shadow-[0_0_10px_rgba(currentcolor,0.8)]`}
                />
             </div>
          </div>
          
          <div className="flex items-center gap-2 mt-4 text-xs text-slate-500">
             <AlertCircle className="w-4 h-4" />
             High certainty prediction
          </div>
        </div>
      </div>

      <div className="mt-auto flex gap-4">
        {downloadUrl && (
          <a
            href={downloadUrl}
            className="flex-1 flex items-center justify-center gap-2 bg-gradient-to-r from-blue-600 to-indigo-600 hover:from-blue-500 hover:to-indigo-500 text-white py-3.5 rounded-xl font-medium shadow-lg shadow-blue-500/25 transition-all"
          >
            <FileDown className="w-5 h-5" />
            Download Image Report
          </a>
        )}
        {onReset && (
          <motion.button
            whileHover={{ scale: 1.02 }}
            whileTap={{ scale: 0.98 }}
            onClick={onReset}
            className="flex-1 glass-button py-3.5 rounded-xl font-medium text-slate-300 hover:text-white"
          >
            Analyze Another Image
          </motion.button>
        )}
      </div>
    </motion.div>
  );
}
